"""
==============================================================================
ATTACK CASE: jmk9800_attackcase5.r2py
==============================================================================
Target NetID:        jmk9800
Original Test:       test16_startswith_vault_bug.r2py
Test File Path:      submit/general_tests/test16_startswith_vault_bug.r2py

RUNNER INFORMATION:
  Runner ID:         runner-5646
  Task UUID:         4f049800-a0d0-47f1-9032-8b08190406fc
  Machine Type:      n2-standard-4
  Execution Server:  http://100.88.83.27:8000

EXECUTION INFORMATION:
  Status:            FAILED
  Start Time:        2025-10-27T19:22:48.584344
  End Time:          2025-10-27T19:22:52.735160
  Runtime:           4.1508 seconds
  Exit Code:         143

FILE HASHES:
  Monitor MD5:       f8ab597a6841526db2f6b6859e1814de
  Attack MD5:        8f001b374ace212a6d5f595dbcbedf6a
  Combined MD5:      4998a325ab65316587292146f0968599

FAILURE DETAILS:
  Reason:            ---
Uncaught exception!
---
Following is a full traceback, and a user traceback.
The user traceback 

STDOUT:
  ---
  Uncaught exception!
  ---
  Following is a full traceback, and a user traceback.
  The user traceback excludes non-user modules. The most recent call is displayed last.
  Full debugging traceback:
    "/app/repy.py", line 134, in execute_namespace_until_completion
    "/app/virtual_namespace.py", line 116, in evaluate
    "/app/safe.py", line 610, in safe_run
    "/app/encasementlib.r2py", line 240, in <module>
    "/app/encasementlib.r2py", line 225, in secure_dispatch
    "/app/namespace.py", line 957, in __do_func_call
    "/app/namespace.py", line 1219, in wrapped_function
    "/app/virtual_namespace.py", line 116, in evaluate
    "/app/safe.py", line 610, in safe_run
    "monitor.r2py", line 129, in <module>
    "/app/encasementlib.r2py", line 175, in _secure_dispatch_closure
    "/app/encasementlib.r2py", line 225, in secure_dispatch
    "/app/namespace.py", line 957, in __do_func_call
    "/app/namespace.py", line 1219, in wrapped_function
    "/app/virtual_namespace.py", line 116, in evaluate
    "/app/safe.py", line 610, in safe_run
    "attack.r2py", line 10, in <module>
    "VMFile wrapper class", line 6, in close
    "wrapper.r2py", line 202, in _wrapped_func
    "monitor.r2py", line 77, in close
  User traceback:
    "/app/encasementlib.r2py", line 240, in <module>
    "/app/encasementlib.r2py", line 225, in secure_dispatch
    "monitor.r2py", line 129, in <module>
    "/app/encasementlib.r2py", line 175, in _secure_dispatch_closure
    "/app/encasementlib.r2py", line 225, in secure_dispatch
    "attack.r2py", line 10, in <module>
    "VMFile wrapper class", line 6, in close
    "wrapper.r2py", line 202, in _wrapped_func
    "monitor.r2py", line 77, in close
  Exception (with type 'exceptions.AttributeError'): VMFile instance has no attribute 'VMfile'
  ---

ORIGINAL TEST DESCRIPTION:
  Targets: aa12037, al8372, bzy205, jaa10243, krg9790, nb4048, sr7991, zs2985
  Vulnerability: Uses startswith() which incorrectly matches "file.vault" when checking for "file.v*"
  Attack: Create "data.vault" then "data" - should not confuse them as versions

==============================================================================
"""

# ============================================================================
# REFERENCE MONITOR CODE (Target: jmk9800)
# ============================================================================
# """
# This security layer inadequately handles the Versioned and Immutable functionality
# 
# Note:
#     This security layer uses encasementlib.r2py, restrictions.default, repy.py and Python
#     Also you need to give it an application to run.
#     python repy.py restrictions.default encasementlib.r2py [security_layer].r2py [attack_program].r2py 
#     
# """
# TYPE = "type"
# ARGS = "args"
# RETURN = "return"
# EXCP = "exceptions"
# TARGET = "target"
# FUNC = "func"  
# OBJC = "objc"
# 
# files = {}
# 
# class VMFile():
#     def __init__(self, filename, create):
#         self.filename = filename
#         if create:
#             found = filename.rfind(".v")
#             if found != -1:
#                 ind = filename.find(".v")
#                 ind += 2
#                 if filename[ind:].isdigit():
#                     raise RepyArgumentError("Cannot create explicit version files")
#             elif filename in listfiles():
#                 # File exists → create version 1
#                 try:
#                     prev_file = openfile(filename, False)
#                     content = prev_file.readat(None, 0)
#                     prev_file.close()
#                 except FileInUseError:
#                     raise FileInUseError
#                 else: 
#                     i = files[filename] + 1
#                     var = "v{}".format(i)
#                     new_name = filename + "." + var
#                     files[filename] += 1
#                     
#                     self.VMfile = openfile(new_name, True)
#                     self.VMfile.writeat(content, 0)
#             else:
#                 # File doesn't exist → create filename
#                 self.VMfile = openfile(filename, True)
#                 files[filename] = 0
#         else:
#             # Open existing file normally
#             try:
#                 self.VMfile = openfile(filename, False)
#             except FileNotFoundError:
#                 raise FileNotFoundError
# 
#     def readat(self, num_bytes, offset):
#         return self.VMfile.readat(num_bytes, offset)
# 
#     def writeat(self, data, offset):
#         found = self.filename.rfind(".v")
#         if found != -1:
#             ind = self.filename.rfind(".v")
#             ind += 2
#             if self.filename[ind:].isdigit():
#                 value = int(self.filename[ind:])
#                 if value < files[self.filename[:ind-2]]:
#                     raise FileInUseError
#         
#         else:
#             if self.filename in files and files[self.filename] > 0:
#                 raise FileInUseError
#             else:
#                 return self.VMfile.writeat(data, offset)
# 
#     def close(self):
#         return self.VMfile.close()
# 
# 
# def LPopenfile(filename, create):
#     return VMFile(filename, create)
# 
# def LPremovefile(filename):
#     raise RepyArgumentError
#     
# 
# def LPlistfiles():
#     all_files = []
#     for file in files.keys():
#         all_files.append(file)
#     return all_files
# 
# 
# # The code below sets up type checking and variable hiding for you.
# # You should not change anything below this point.
# sec_file_def = {
#     "obj-type": VMFile,
#     "name": "VMFile",
#     "writeat": {"type": "func", "args": (str, (int, long)), "exceptions": Exception, "return": (int, type(None)), "target": VMFile.writeat},
#     "readat": {"type": "func", "args": ((int, long, type(None)), (int, long)), "exceptions": Exception, "return": str, "target": VMFile.readat},
#     "close": {"type": "func", "args": None, "exceptions": Exception, "return": (bool, type(None)), "target": VMFile.close}
# }
# 
# CHILD_CONTEXT_DEF["openfile"] = {
#     TYPE: OBJC,
#     ARGS: (str, bool),
#     EXCP: Exception,
#     RETURN: sec_file_def,
#     TARGET: LPopenfile
# }
# 
# CHILD_CONTEXT_DEF["removefile"] = {
#     TYPE: FUNC,
#     ARGS: (str,),
#     EXCP: Exception,
#     RETURN: type(None),
#     TARGET: LPremovefile
# }
# 
# CHILD_CONTEXT_DEF["listfiles"] = {
#     TYPE: FUNC,
#     ARGS: None,
#     EXCP: Exception,
#     RETURN: list,
#     TARGET: LPlistfiles
# }
# 
# # Execute the user code
# secure_dispatch_module()
# ============================================================================

# Create file with .v in name but not a version
f1 = openfile("data.vault", True)
f1.writeat("vault_data", 0)
f1.close()

# Create file with same prefix
f2 = openfile("data", True)
f2.writeat("base_data", 0)
f2.close()

# Create version of data - should copy from "data", not "data.vault"
f3 = openfile("data", True)
content = f3.readat(None, 0)
if content != "base_data":
    log("ERROR: Should copy from data, not data.vault\n")
    exitall()
f3.close()

# Both should be in listfiles
files = listfiles()
if "data" not in files:
    log("ERROR: data should be in listfiles\n")
    exitall()
if "data.vault" not in files:
    log("ERROR: data.vault should be in listfiles\n")
    exitall()
